parser: '@typescript-eslint/parser'

extends:
  - plugin:@typescript-eslint/recommended
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.json

rules:
  '@typescript-eslint/typedef':
    - error
  '@typescript-eslint/semi':
    - error
    - never  

settings:
  react:
    version: detect
